var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                   x       x                    ",
   "                                    o o      x             x                    ",
   "                                                           x                    ",
   "                                    xx                     x                    ",
   "                                                           x       xpppppp  xx  ",
   "  xx                                      o o              x       p         x  ",
   "  x                     o                                  x   x   p         x  ",
   "  x           xx                         xxxxx             x       p       ? x  ",
   "  x          xxxx       o                                  x       p         x  ",
   "  x  @       xxxx                                          x     xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxx        xxxxxxx   xxxxxxxxx  ",
   "                              x   x               x!!!!!!!!x                    ",
   "                              x!!!x               x!!!!!!!!x                    ",
   "                              x!!!x               x!!!!!!!!x                    ",
   "                              xxxxx               xxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                  xxxxxxx                                    xpx  ",
   "                                      xxxx                     xxxx     xxxx                                 xpx  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                xpx  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               xpx  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   ?  xpx  ",
   "                                                xx!x         x     o   o                                    xxpx  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxxppx  ",
   "                                                 xvx         x     x   x                        ppppppppppppppxx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xxpppppppppppxx            v                        ",
   "                                                               xxxxpppppxxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x            v              x x    =    x x                  ",
   " x        x                                    x     x                             x         x                    ",
   " v        v                                    x     x                             xx        x                    ",
   "                                               xx    x                       x     x         x                    ",
   "                                               x     x      o  o     x o x         x    =   xx                    ",
   "               x     x   =    xxx   xxx        x     x               x o x         x         x                    ",
   "              xxpppppxx         x   x          x     x     xxxxxx    x o x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x o x   x               x                    ",
   "     @       x         x        x   x          x     x            x  x o x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x o xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x o   o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x o   =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxx    x!!!!!!!xx!     xxxxxxpxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx  =  xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x             =       xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xx xxx xx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                        x                      p  p                                           ",
   "                                        x                   p        p                                        ",
   "                                        x                   pp      pp                                         ",
   "                                        x                     pppppp                                          ",
   "                                       xxx                                                                    ",
   "                                       x x                                 xxx                                ",
   "                                       x x                  x          x    |                                 ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x    ?     x      xpppx                           ",
   "                                      x   x                 x!!xxxxxx!!x       xxx                            ",
   "                                     xx   xx     =x   x=     x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x     o     xpppx                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x     o               xpppx                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx!xxx xxx xxx     o o  xppppppppppppppx                   vx                   ",
   "                             x xxx x x xxx x          xppppppppppppppx                                        ",
   "                             x      =      x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x    oxo    x                                         xpppx                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       xpppx          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xx!!xxxxx!!xx  x oo x    x oo x    x oo  xx xx        |           xxx        x  ",
   "  x      @         =x=        x           x!!x    x!!!!x    x!!!!x    xx   xx                    x =       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
